// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC916pppRjLs6N-nsj4wAp_Q-XLVyRipNQ',
    appId: '1:654846208029:web:755d94e150af86da5e7ef4',
    messagingSenderId: '654846208029',
    projectId: 'geliyortrapp',
    authDomain: 'geliyortrapp.firebaseapp.com',
    storageBucket: 'geliyortrapp.firebasestorage.app',
    measurementId: 'G-4PBPTDYMBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhbvJHGnCpKNTco8ZiIGjnNy_qGBkGYQ',
    appId: '1:654846208029:android:e6c2436221cb60b75e7ef4',
    messagingSenderId: '654846208029',
    projectId: 'geliyortrapp',
    storageBucket: 'geliyortrapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaLoHEosm2D090JGr015f1WVOZ-spfRMA',
    appId: '1:654846208029:ios:c8ab355b046b291e5e7ef4',
    messagingSenderId: '654846208029',
    projectId: 'geliyortrapp',
    storageBucket: 'geliyortrapp.firebasestorage.app',
    iosBundleId: 'com.geliyor.mobil',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaLoHEosm2D090JGr015f1WVOZ-spfRMA',
    appId: '1:654846208029:ios:9f7954d01dab48945e7ef4',
    messagingSenderId: '654846208029',
    projectId: 'geliyortrapp',
    storageBucket: 'geliyortrapp.firebasestorage.app',
    iosBundleId: 'com.geliyor.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC916pppRjLs6N-nsj4wAp_Q-XLVyRipNQ',
    appId: '1:654846208029:web:755d94e150af86da5e7ef4',
    messagingSenderId: '654846208029',
    projectId: 'geliyortrapp',
    authDomain: 'geliyortrapp.firebaseapp.com',
    storageBucket: 'geliyortrapp.firebasestorage.app',
    measurementId: 'G-4PBPTDYMBX',
  );
}
